-- ============================================================
--  V1 — Initial schema
--  Project: scentcepts
--  Generated by Sprygen on 2026-04-07
-- ============================================================

CREATE TABLE IF NOT EXISTS users (
    id              UUID                PRIMARY KEY,
    first_name      VARCHAR(100)        NOT NULL,
    last_name       VARCHAR(100)        NOT NULL,
    email           VARCHAR(255) UNIQUE NOT NULL,
    password        VARCHAR(255)        NOT NULL,
    phone_number    VARCHAR(50),
    address         TEXT,
    bio             TEXT,
    avatar_url      VARCHAR(500),
    deleted_at      TIMESTAMPTZ,
    created_at      TIMESTAMPTZ         NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ         NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by      VARCHAR(255),
    last_modified_by VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS user_roles (
    user_id   UUID      NOT NULL,
    role_name VARCHAR(50) NOT NULL,
    PRIMARY KEY (user_id, role_name),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
