-- ============================================================
--  V2__create_brand_table
--  Entity: Brand
--  Generated by Sprygen on 2026-04-07
-- ============================================================

CREATE TABLE IF NOT EXISTS brands (
    id               UUID                PRIMARY KEY,
    name             VARCHAR(255)        NOT NULL,
    logo_url         VARCHAR(500),
    deleted_at       TIMESTAMPTZ,
    created_at       TIMESTAMPTZ         NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMPTZ         NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by       VARCHAR(255),
    last_modified_by VARCHAR(255)
);
