-- ============================================================
--  V4__create_scentOrder_table
--  Entity: ScentOrder
--  Generated by Sprygen on 2026-04-07
-- ============================================================

CREATE TABLE IF NOT EXISTS scent_orders (
    id               UUID                PRIMARY KEY,
    total_amount     DECIMAL(19,2)       NOT NULL,
    status           VARCHAR(50)         NOT NULL DEFAULT 'PENDING',
    delivery_address TEXT,
    user_id          UUID,
    created_at       TIMESTAMPTZ         NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMPTZ         NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by       VARCHAR(255),
    last_modified_by VARCHAR(255),
    FOREIGN KEY (user_id) REFERENCES users(id)
);
