-- ============================================================
--  V3__create_product_table
--  Entity: Product
--  Generated by Sprygen on 2026-04-07
-- ============================================================

CREATE TABLE IF NOT EXISTS products (
    id                UUID                PRIMARY KEY,
    name              VARCHAR(255)        NOT NULL,
    description       TEXT,
    top_notes         VARCHAR(255),
    middle_notes      VARCHAR(255),
    base_notes        VARCHAR(255),
    decant_price      DECIMAL(19,2)       NOT NULL,
    full_bottle_price DECIMAL(19,2)       NOT NULL,
    image_url         VARCHAR(500),
    stock_quantity    INT                 NOT NULL DEFAULT 0,
    availability      VARCHAR(50)         NOT NULL DEFAULT 'IN_STOCK',
    brand_id          UUID,
    deleted_at        TIMESTAMPTZ,
    created_at        TIMESTAMPTZ         NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMPTZ         NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by        VARCHAR(255),
    last_modified_by  VARCHAR(255),
    FOREIGN KEY (brand_id) REFERENCES brands(id)
);
