-- ============================================================
--  V5__create_orderItem_table
--  Entity: OrderItem
--  Generated by Sprygen on 2026-04-07
-- ============================================================

CREATE TABLE IF NOT EXISTS order_items (
    id                UUID                PRIMARY KEY,
    size              VARCHAR(50)         NOT NULL,
    quantity          INT                 NOT NULL DEFAULT 1,
    price_at_purchase DECIMAL(19,2)       NOT NULL,
    order_id          UUID,
    product_id        UUID,
    created_at        TIMESTAMPTZ         NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMPTZ         NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by        VARCHAR(255),
    last_modified_by  VARCHAR(255),
    FOREIGN KEY (order_id) REFERENCES scent_orders(id),
    FOREIGN KEY (product_id) REFERENCES products(id)
);
